### ISSUE TITLE
请教一下启动报错！

### ISSUE THREAD

**Issue by ronnieyuyiwei** [waynecz/vue-img-inputer#20]
npm install 后
npm run start 报错
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-img-inputer@1.1.0 start: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-img-inputer@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

求教一下是什么原因，谢谢！

**Comment by waynecz** [comment]
@ronnieyuyiwei  是 `npm start` 哦

**Comment by ronnieyuyiwei** [comment]
修改后依旧有错。。
bash-3.2# npm start

> vue-img-inputer@1.1.0 start /Users/swallow/develop/vue-img-inputer
> node build/dev-server.js

> Starting dev server...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8888
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:14)
    at listenInCluster (net.js:1353:12)
    at Server.listen (net.js:1453:7)
    at Function.listen (/Users/swallow/develop/vue-img-inputer/node_modules/_express@4.15.3@express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/swallow/develop/vue-img-inputer/build/dev-server.js:82:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-img-inputer@1.1.0 start: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-img-inputer@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/swallow/.npm/_logs/2017-07-13T15_56_35_529Z-debug.log

**Comment by waynecz** [comment]
可以看下你的 node 版本吗

```
node --version
```

**Comment by ronnieyuyiwei** [comment]
@waynecz v8.0.0

**Comment by waynecz** [comment]
哦哦哦，看了下可能是 8888 端口被占用了
```
lsof -i:8888
```

看看有没有进程占用了

**Comment by ronnieyuyiwei** [comment]
我在配置文件中尝试修改至端口8488，终端显示bash-3.2# npm start

> vue-img-inputer@1.1.0 start /Users/swallow/develop/vue-img-inputer
> node build/dev-server.js

> Starting dev server...


 DONE  Compiled successfully in 8367ms                                                            14:30:16

> Listening at http://localhost:8488

浏览器访问 http://localhost:8488，然而显示为 Cannot GET /

**Comment by ByWhiter** [comment]
我也是 启动npm start 报Cannot GET /

**Comment by ByWhiter** [comment]
@waynecz  大神请问这个是怎么回事

**Comment by waynecz** [comment]
@ByWhiter 项目更新了下， 删掉原项目重新 clone 即可解决

**Comment by ByWhiter** [comment]
@谢谢，插件不错，以后我也得努力写一个自己的了
